'use strict';
const {createApp, ref, h, nextTick, defineComponent} = Vue;
const $=s=>document.querySelector(s), modal=$('#modal');
const screen = ref({kind:'login', html:''});
// Vue owns the application root. Legacy presentation functions return escaped HTML.
const LoginView = defineComponent({name:'LoginView', props:['html'], setup: props => () => h('div',{innerHTML:props.html})});
const CondominiumView = defineComponent({name:'CondominiumView', props:['html'], setup: props => () => h('div',{innerHTML:props.html})});
const app = {set innerHTML(html){screen.value={kind:user?'community':'login',html};}};

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateText=s=>new Date(s+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'});
const areas=[{id:'salao',name:'Salão de festas',capacity:'40 pessoas',symbol:'♧',desc:'Um espaço para celebrar com família e amigos.',rules:'Das 08h às 22h. Entregue o espaço limpo e respeite a capacidade.'},{id:'churrasqueira',name:'Churrasqueira',capacity:'16 pessoas',symbol:'♨',desc:'Almoço de domingo ou encontro com os vizinhos.',rules:'Das 08h às 22h. Recolha o lixo e desligue os equipamentos ao sair.'},{id:'quadra',name:'Quadra esportiva',capacity:'12 pessoas',symbol:'◈',desc:'Mais movimento e lazer para a sua rotina.',rules:'Das 08h às 22h. Use calçado adequado e preserve os equipamentos.'}];
const initial=()=>({notices:[{id:'n1',title:'Manutenção dos elevadores',category:'Manutenção',text:'Na próxima segunda-feira, das 9h às 12h, os elevadores passarão por manutenção preventiva. Um equipamento permanecerá disponível durante o serviço.',date:day()},{id:'n2',title:'Nosso próximo encontro de moradores',category:'Comunidade',text:'Vamos conversar sobre melhorias nas áreas comuns. O encontro será no salão de festas, no próximo sábado, às 10h. Sua participação é bem-vinda.',date:day(-1)},{id:'n3',title:'Cuidar dos espaços é cuidar de todos',category:'Convivência',text:'Após utilizar a churrasqueira, confira os equipamentos e recolha seus objetos. Pequenos cuidados fazem a diferença na nossa convivência.',date:day(-2)}],bookings:[{id:'b1',area:'salao',date:day(2),start:'14:00',end:'16:00',owner:'vizinho',name:'Morador demonstrativo'},{id:'b2',area:'churrasqueira',date:day(4),start:'12:00',end:'14:00',owner:'morador',name:'Marina Oliveira'}],messages:[]});
let state;try{state=JSON.parse(localStorage.getItem('condofacil-demo-v1'))}catch{}if(!state?.notices||!state?.bookings||!state?.messages)state=initial();
let user=null,view='inicio',pending=null;const save=()=>{try{localStorage.setItem('condofacil-demo-v1',JSON.stringify(state))}catch{toast('Não foi possível salvar neste navegador. A demonstração continua nesta sessão.')}};
const areaName=id=>areas.find(a=>a.id===id)?.name||id;const mine=()=>state.bookings.filter(b=>user.role==='admin'||b.owner===user.id).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200)}
function openModal(title,html){modal.innerHTML=`<div class="modalhead"><h2 id="dialog-title">${esc(title)}</h2><button aria-label="Fechar" data-action="close">×</button></div>${html}`;modal.setAttribute('aria-labelledby','dialog-title');modal.showModal()}
function login(){app.innerHTML=`<div class="login"><section class="login-left"><div class="brand"><span class="mark">⌂</span>CondoFácil</div><div><div class="eyebrow" style="color:#cde694">VIVER BEM, EM COMUNIDADE</div><h1>Seu condomínio.<br>Mais perto de você.</h1><p>Avisos, reservas e conversas em um lugar só.</p></div><footer>Residencial Castelo de Mônaco · Ambiente demonstrativo</footer></section><section class="login-right"><div class="login-box"><div class="eyebrow">BEM-VINDO AO CONDOFÁCIL</div><h1>Entre na sua comunidade</h1><p class="muted">Escolha um perfil para explorar o protótipo.</p><div class="role-buttons"><button data-action="enter" data-role="morador">Entrar como morador</button><button class="secondary" data-action="enter" data-role="admin">Administração</button></div><div class="hint"><strong>Demonstração acadêmica</strong><br>Não é necessário informar senha. Todos os nomes e dados são fictícios. Alterações ficam somente neste navegador.</div><button class="ghost" style="margin-top:20px" data-action="signup">Simular novo cadastro →</button></div></section></div>`}
const menus=[['inicio','⌂','Visão geral'],['avisos','▤','Avisos'],['areas','◇','Áreas comuns'],['reservas','▦','Minhas reservas'],['mensagens','✉','Mensagens'],['informacoes','ⓘ','O condomínio']];
function navigate(v){if(!menus.some(m=>m[0]===v))throw Error('Tela inválida');view=v;if(user){render();nextTick(()=>$('#main')?.focus());}return {tela:v}}
function render(){if(!user)return login();const label=menus.find(m=>m[0]===view)[2];app.innerHTML=`<a class="skip-link" href="#main" data-action="focus-main">Pular para o conteúdo</a><div class="shell"><aside class="sidebar"><div class="brand"><span class="mark">⌂</span>CondoFácil</div><div class="community"><strong>Residencial Castelo de Mônaco</strong><small>Residencial demonstrativo</small></div><nav aria-label="Navegação principal">${menus.map(([id,ico,name])=>`<a href="#${id}" ${id===view?'aria-current="page"':''} class="${id===view?'active':''}"><span class="navicon">${ico}</span>${id==='reservas'&&user.role==='admin'?'Reservas':name}</a>`).join('')}</nav><div class="sidebarfoot"><button class="secondary" style="width:100%" data-action="switch">Trocar perfil</button><p>Protótipo navegável<br>Dados locais e demonstrativos</p><button class="ghost small" data-action="reset">Restaurar demonstração</button></div></aside><div><header class="topbar"><span class="demo">Condomínio / ${label}</span><span class="mobilebrand">CondoFácil</span><div class="row"><div class="avatar">${user.role==='admin'?'AD':esc(user.name.charAt(0))}</div><div class="profile"><strong>${esc(user.name)}</strong><small>${user.role==='admin'?'Administração':'Morador · Unidade demonstrativa 204'}</small></div><button class="ghost" data-action="switch">Sair</button></div></header><main class="content" id="main" tabindex="-1">${page()}</main></div></div>`}
function notice(n,full=true){return `<article class="notice"><div class="row between"><span class="badge ${n.category==='Manutenção'?'amber':n.category==='Comunidade'?'blue':''}">${esc(n.category)}</span><time>${dateText(n.date)}</time></div><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${user.role==='admin'&&full?`<button class="textlink" data-action="edit-notice" data-id="${n.id}">Editar comunicado</button>`:''}</article>`}
function booking(b,cancel=false){return `<article class="booking"><div class="datebox">${new Date(b.date+'T12:00').toLocaleDateString('pt-BR',{month:'short'})}<strong>${b.date.slice(-2)}</strong></div><div style="flex:1"><h3>${areaName(b.area)}</h3><p>${b.start} às ${b.end}${user.role==='admin'?' · '+esc(b.name):''}</p><div class="row between wrap" style="margin-top:8px"><span class="status">Confirmada</span>${cancel?`<button class="textlink" data-action="cancel-booking" data-id="${b.id}">Cancelar reserva</button>`:''}</div></div></article>`}
function pagehead(title,sub,button=''){return `<div class="pagehead"><div><div class="eyebrow">CASTELO DE MÔNACO</div><h1>${title}</h1><p>${sub}</p></div>${button}</div>`}
function page(){switch(view){case'inicio':return `${pagehead('Olá, '+esc(user.name.split(' ')[0])+'.','Tudo o que você precisa, mais perto.')}<section class="welcome"><div><h2>Um espaço para o seu próximo encontro.</h2><p>Confira as áreas comuns e reserve um horário para aproveitar.</p></div><button data-action="go" data-view="areas">Reservar um espaço +</button></section><div class="stats"><article class="stat"><div class="row">▤ &nbsp; Avisos publicados</div><div class="number">${state.notices.length.toString().padStart(2,'0')}</div><small>Fique por dentro da comunidade</small></article><article class="stat"><div class="row">▦ &nbsp; ${user.role==='admin'?'Reservas ativas':'Suas reservas'}</div><div class="number">${mine().length.toString().padStart(2,'0')}</div><small>Momentos já agendados</small></article><article class="stat"><div class="row">◇ &nbsp; Áreas comuns</div><div class="number">03</div><small>Espaços para compartilhar</small></article></div><div class="columns"><section class="card"><div class="cardhead"><h2>Acontece no condomínio</h2><button class="textlink" data-action="go" data-view="avisos">Ver todos</button></div>${state.notices.slice(0,2).map(n=>notice(n,false)).join('')}</section><section class="card"><div class="cardhead"><h2>Próximas reservas</h2></div>${mine().slice(0,3).map(b=>booking(b)).join('')||'<div class="empty">Você ainda não tem reservas.</div>'}<button class="secondary" style="width:100%;margin-top:16px" data-action="go" data-view="reservas">Acompanhar reservas</button></section></div>`;
case'avisos':return `${pagehead('Mural de avisos','Informações importantes para o dia a dia.',user.role==='admin'?'<button data-action="new-notice">+ Publicar aviso</button>':'')}<section class="card">${state.notices.map(n=>notice(n)).join('')||'<div class="empty">Nenhum aviso publicado.</div>'}</section>`;
case'areas':return `${pagehead('Espaços para aproveitar','Escolha uma área e consulte os horários disponíveis.')}<div class="area-grid">${areas.map(a=>`<article class="card area"><div class="area-top"><span class="symbol">${a.symbol}</span><span class="badge">${a.capacity}</span></div><div class="area-body"><h2>${a.name}</h2><p>${a.desc}</p><small class="muted">Aberto das 08h às 22h</small><button data-action="reserve" data-area="${a.id}">Consultar e reservar</button></div></article>`).join('')}</div><div class="hint">As reservas são por horário. O espaço deve ser entregue organizado ao fim do período. Confira as regras antes de confirmar.</div>`;
case'reservas':return `${pagehead(user.role==='admin'?'Reservas do condomínio':'Minhas reservas','Seus próximos momentos nas áreas comuns.','<button data-action="go" data-view="areas">+ Nova reserva</button>')}<section class="card">${mine().map(b=>booking(b,true)).join('')||'<div class="empty"><h3>A agenda está livre por aqui</h3><p>Escolha uma área comum para fazer sua primeira reserva.</p><button data-action="go" data-view="areas">Explorar espaços</button></div>'}</section>`;
case'mensagens':{const messages=state.messages.filter(m=>user.role==='admin'||m.owner===user.id);return `${pagehead(user.role==='admin'?'Caixa de mensagens':'Fale com a administração','Um canal para dúvidas, sugestões e solicitações.',user.role==='morador'?'<button data-action="new-message">+ Nova mensagem</button>':'')}<section class="card">${messages.map(m=>`<article class="notice"><div class="row between"><span class="badge">${m.reply?'Respondida':'Enviada'}</span><small>${dateText(m.date)}</small></div><h3>${esc(m.subject)}</h3>${user.role==='admin'?`<small>De ${esc(m.name)}</small>`:''}<p>${esc(m.text)}</p>${m.reply?`<div class="hint"><strong>Administração</strong><p class="message-body">${esc(m.reply)}</p></div>`:user.role==='admin'?`<button class="secondary" data-action="reply" data-id="${m.id}">Responder</button>`:'<small class="muted">Aguardando resposta da administração.</small>'}</article>`).join('')||'<div class="empty"><h3>Nenhuma conversa por enquanto</h3><p>As mensagens desta demonstração aparecem aqui e no perfil da administração.</p></div>'}</section>`}
case'informacoes':return `${pagehead('Nosso condomínio','Informações úteis, sempre à mão.')}<div class="columns"><section class="card info-list"><h2>Regras de convivência</h2><p><strong>Horário de silêncio</strong><br><span class="muted">Das 22h às 8h. Respeite o descanso dos vizinhos.</span></p><p><strong>Áreas comuns</strong><br><span class="muted">Uso mediante reserva, das 8h às 22h. Não exceda a capacidade do espaço.</span></p><p><strong>Descarte de resíduos</strong><br><span class="muted">Separe recicláveis e utilize os locais identificados.</span></p><p><strong>Pets</strong><br><span class="muted">Circule com guia e recolha os resíduos nas áreas compartilhadas.</span></p></section><section class="card"><h2>Residencial Castelo de Mônaco</h2><p>Av. Sen. Antônio Mendes Canale, 1159 - Pioneiros, Campo Grande - MS.</p><h3>Administração demonstrativa</h3><p class="muted">Atendimento de segunda a sexta, das 8h às 17h.</p><button data-action="go" data-view="mensagens">Abrir mensagens</button><div class="hint"><strong>Sobre esta demonstração</strong><br>Protótipo acadêmico independente. Pessoas, avisos e regras demonstrativos. Não há envio de mensagens externas, autenticação real ou sincronização entre dispositivos.</div></section></div>`}}
function reserve(id){const a=areas.find(a=>a.id===id);openModal('Reservar '+a.name,`<p class="muted">${a.rules}</p><form id="reserve-form"><input type="hidden" name="area" value="${id}"><div class="field"><label for="date">Data</label><input id="date" name="date" type="date" min="${day()}" value="${day(1)}" required></div><div id="busy" class="hint" style="margin:0 0 18px"></div><div class="half"><div class="field"><label for="start">Início</label><input id="start" name="start" type="time" min="08:00" max="22:00" step="1800" value="10:00" required></div><div class="field"><label for="end">Término</label><input id="end" name="end" type="time" min="08:00" max="22:00" step="1800" value="12:00" required></div></div><div class="error" id="form-error" role="alert"></div><button style="width:100%">Conferir reserva</button></form>`);$('#date').addEventListener('change',()=>busy(id,$('#date').value));busy(id,$('#date').value)}
function busy(id,date){const list=state.bookings.filter(b=>b.area===id&&b.date===date);$('#busy').textContent=list.length?'Horários ocupados: '+list.map(b=>b.start+' às '+b.end).join(', '):'Nenhuma reserva neste dia. Escolha seu horário.'}
function bookingError(b){if(!b.date||!b.start||!b.end)return 'Preencha a data e os horários.';if(b.date<day()||new Date(b.date+'T'+b.start)<new Date())return 'Escolha um horário no futuro.';if(b.start<'08:00'||b.end>'22:00'||b.start>=b.end)return 'Use um intervalo válido entre 08h e 22h.';if(state.bookings.some(x=>x.area===b.area&&x.date===b.date&&b.start<x.end&&b.end>x.start))return 'Esse período já está ocupado. Escolha outro horário.';return ''}
function noticeForm(id){const n=state.notices.find(n=>n.id===id);openModal(n?'Editar aviso':'Novo aviso',`<form id="notice-form"><input type="hidden" name="id" value="${id||''}"><div class="field"><label for="title">Título</label><input id="title" name="title" maxlength="100" required value="${esc(n?.title||'')}"></div><div class="field"><label for="category">Categoria</label><select name="category" id="category">${['Comunidade','Manutenção','Convivência'].map(c=>`<option ${n?.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label for="text">Comunicado</label><textarea name="text" id="text" maxlength="1500" required>${esc(n?.text||'')}</textarea></div><button>Salvar aviso</button></form>`)}
function handleClick(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='focus-main'){e.preventDefault();$('#main')?.focus();return;}if(a==='enter'){user=b.dataset.role==='admin'?{role:'admin',id:'admin',name:'Administração'}:{role:'morador',id:'morador',name:'Marina Oliveira'};view='inicio';render()}if(a==='close')modal.close();if(a==='switch'){user=null;view='inicio';login()}if(a==='go')navigate(b.dataset.view);if(a==='reserve')reserve(b.dataset.area);if(a==='new-notice'&&user.role==='admin')noticeForm();if(a==='edit-notice'&&user.role==='admin')noticeForm(b.dataset.id);if(a==='reset')openModal('Restaurar demonstração','<p>Isso remove as alterações deste navegador e recupera os dados de exemplo.</p><div class="actions"><button class="secondary" data-action="close">Voltar</button><button data-action="confirm-reset">Restaurar</button></div>');if(a==='confirm-reset'){state=initial();save();modal.close();render();toast('Dados demonstrativos restaurados.')}if(a==='confirm-reserve'){const err=bookingError(pending);if(err){modal.close();toast(err);return}state.bookings.push({...pending,id:crypto.randomUUID(),owner:user.id,name:user.name});save();pending=null;modal.close();navigate('reservas');toast('Reserva confirmada nesta demonstração.')}if(a==='cancel-booking')openModal('Cancelar reserva','<p>Deseja liberar este horário?</p><div class="actions"><button class="secondary" data-action="close">Manter reserva</button><button class="danger" data-action="confirm-cancel" data-id="'+b.dataset.id+'">Cancelar reserva</button></div>');if(a==='confirm-cancel'){state.bookings=state.bookings.filter(x=>!(x.id===b.dataset.id&&(user.role==='admin'||x.owner===user.id)));save();modal.close();render();toast('Reserva cancelada.')}if(a==='new-message')openModal('Nova mensagem','<form id="message-form"><div class="field"><label for="subject">Assunto</label><input id="subject" name="subject" required maxlength="100"></div><div class="field"><label for="message">Como podemos ajudar?</label><textarea id="message" name="text" required maxlength="1500"></textarea></div><p class="small muted">Mensagem demonstrativa. Não inclua informações pessoais.</p><button>Enviar mensagem</button></form>');if(a==='reply'&&user.role==='admin')openModal('Responder mensagem','<form id="reply-form"><input type="hidden" name="id" value="'+b.dataset.id+'"><div class="field"><label for="reply">Resposta</label><textarea id="reply" name="reply" required maxlength="1500"></textarea></div><button>Enviar resposta</button></form>');if(a==='signup')openModal('Cadastro demonstrativo','<form id="signup-form"><p class="muted">Crie um perfil fictício para navegar. Nenhuma conta real será criada.</p><div class="field"><label for="name">Nome de demonstração</label><input id="name" name="name" required maxlength="50" placeholder="Ex.: Alex Silva"></div><button>Criar perfil e entrar</button></form>')}
function handleSubmit(e){const f=e.target;e.preventDefault();const d=Object.fromEntries(new FormData(f));if(Object.values(d).some(v=>typeof v==='string'&&v.length>1600))return; if(f.getAttribute('id')==='reserve-form'){const err=bookingError(d);if(err){$('#form-error').textContent=err;return}pending=d;modal.close();openModal('Confira sua reserva',`<p>Está tudo certo para o seu encontro?</p><div class="summary"><h3>${areaName(d.area)}</h3><p>${dateText(d.date)}</p><p>${d.start} às ${d.end}</p></div><p class="small muted">Ao confirmar, você concorda com as regras de uso do espaço.</p><div class="actions"><button class="secondary" data-action="close">Cancelar</button><button data-action="confirm-reserve">Confirmar reserva</button></div>`)}if(f.getAttribute('id')==='notice-form'&&user.role==='admin'){if(!d.title.trim()||!d.text.trim())return toast('Preencha o título e o comunicado.');const n={id:d.id||crypto.randomUUID(),title:d.title.trim(),text:d.text.trim(),category:d.category,date:day()};if(d.id)state.notices=state.notices.map(x=>x.id===d.id?n:x);else state.notices.unshift(n);save();modal.close();render();toast('Aviso salvo.')}if(f.getAttribute('id')==='message-form'){if(!d.text.trim()||!d.subject.trim())return toast('Preencha o assunto e a mensagem.');state.messages.unshift({...d,id:crypto.randomUUID(),owner:user.id,name:user.name,date:day(),reply:''});save();modal.close();render();toast('Mensagem adicionada à demonstração.')}if(f.getAttribute('id')==='reply-form'&&user.role==='admin'){if(!d.reply.trim())return;state.messages.find(x=>x.id===d.id).reply=d.reply.trim();save();modal.close();render();toast('Resposta enviada.')}if(f.getAttribute('id')==='signup-form'){if(!d.name.trim())return;user={id:crypto.randomUUID(),role:'morador',name:d.name.trim()};modal.close();navigate('inicio');toast('Perfil temporário criado.')}}
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(menus.some(m=>m[0]===v))navigate(v)});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'navigate_condofacil',description:'Abre uma tela do protótipo após entrar em um perfil.',inputSchema:{type:'object',properties:{tela:{type:'string',enum:menus.map(m=>m[0])}},required:['tela'],additionalProperties:false},execute:({tela})=>{if(!user)throw Error('Entre em um perfil primeiro.');return navigate(tela)}})}catch{}}
// Framework components own event handling for all six application views.
createApp({name:'CondoFacilApp',setup(){return ()=>h('div',{onClick:handleClick,onSubmit:handleSubmit},[
 h(screen.value.kind==='login'?LoginView:CondominiumView,{html:screen.value.html})
]);}}).mount('#app');
// Native dialog remains outside the root to preserve browser focus trapping.
modal.addEventListener('click', handleClick);
modal.addEventListener('submit', handleSubmit);
login();
